version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://user:password@db:5432/db_name

  db:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=sanjay
      - POSTGRES_PASSWORD=sanjay123
      - POSTGRES_DB=sp_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
